#  TinyPedal is an open-source overlay application for racing simulation.
#  Copyright (C) 2022-2026 TinyPedal developers, see contributors.md file
#
#  This file is part of TinyPedal.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Default setting of brake widgets

Widget key name must match corresponding file name in 'widget' folder
"""

from ..setting_heatmap import HEATMAP_DEFAULT_BRAKE

WIDGET_BRAKES = {
        "brake_bias": {
        "enable": False,
        "update_interval": 20,
        "position_x": 593,
        "position_y": 292,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 1,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_brake_bias": True,
        "decimal_places_brake_bias": 2,
        "prefix_brake_bias": "BB ",
        "font_color_brake_bias": "#FFFFFF",
        "background_color_brake_bias": "#222222",
        "show_front_and_rear": False,
        "show_percentage_sign": True,
        "show_baseline_bias_delta": True,
        "decimal_places_baseline_bias_delta": 2,
        "prefix_baseline_bias_delta": "",
        "font_color_baseline_bias_delta": "#FFFFFF",
        "background_color_baseline_bias_delta": "#222222",
        "show_brake_migration": True,
        "decimal_places_brake_migration": 1,
        "prefix_brake_migration": "BM ",
        "suffix_brake_migration": "F",
        "font_color_brake_migration": "#FFFFFF",
        "background_color_brake_migration": "#222222",
        "electric_braking_allocation": -1,
        "display_order_brake_bias": 1,
        "display_order_baseline_bias_delta": 2,
        "display_order_brake_migration": 3,
    },
        "brake_performance": {
        "enable": False,
        "update_interval": 20,
        "position_x": 57,
        "position_y": 753,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_transient_maximum_braking_rate": True,
        "font_color_transient_maximum_braking_rate": "#FFFFFF",
        "background_color_transient_maximum_braking_rate": "#222222",
        "show_maximum_braking_rate": True,
        "font_color_maximum_braking_rate": "#000000",
        "background_color_maximum_braking_rate": "#DDDDDD",
        "show_delta_braking_rate": True,
        "show_delta_braking_rate_in_percentage": True,
        "font_color_delta_braking_rate": "#FFFFFF",
        "background_color_delta_braking_rate": "#222222",
        "background_color_braking_rate_gain": "#008800",
        "background_color_braking_rate_loss": "#CC7700",
        "show_front_wheel_lock_duration": True,
        "font_color_front_wheel_lock_duration": "#FFFFFF",
        "background_color_front_wheel_lock_duration": "#222222",
        "show_rear_wheel_lock_duration": True,
        "font_color_rear_wheel_lock_duration": "#FFFFFF",
        "background_color_rear_wheel_lock_duration": "#222222",
        "display_order_transient_maximum_braking_rate": 1,
        "display_order_maximum_braking_rate": 2,
        "display_order_delta_braking_rate": 3,
        "display_order_front_wheel_lock_duration": 4,
        "display_order_rear_wheel_lock_duration": 5,
    },
        "brake_pressure": {
        "enable": False,
        "update_interval": 20,
        "position_x": 253,
        "position_y": 476,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "highlight_color": "#00AAFF",
        "background_color": "#222222",
        "show_brake_input": True,
        "brake_input_size": 3,
        "brake_input_color": "#00AAFF",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "brake pres",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
        "brake_temperature": {
        "enable": False,
        "update_interval": 20,
        "position_x": 460,
        "position_y": 525,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "swap_style": False,
        "show_degree_sign": False,
        "leading_zero": 2,
        "font_color_temperature": "#000000",
        "background_color_temperature": "#222222",
        "enable_heatmap_auto_matching": True,
        "heatmap_name": HEATMAP_DEFAULT_BRAKE,
        "show_average": True,
        "average_sampling_duration": 10,
        "off_brake_duration": 1,
        "font_color_average": "#AAAAAA",
        "background_color_average": "#222222",
        "display_order_temperature": 1,
        "display_order_average": 2,
    },
        "brake_wear": {
        "enable": False,
        "update_interval": 20,
        "position_x": 688,
        "position_y": 720,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_thickness": False,
        "warning_threshold_remaining": 30,
        "warning_threshold_wear": 1,
        "warning_threshold_laps": 5,
        "warning_threshold_minutes": 6,
        "font_color_warning": "#FF2200",
        "show_remaining": True,
        "font_color_remaining": "#22CC22",
        "background_color_remaining": "#222222",
        "show_wear_difference": True,
        "font_color_wear_difference": "#CCCCCC",
        "background_color_wear_difference": "#222222",
        "show_live_wear_difference": False,
        "font_color_live_wear_difference": "#CCCCCC",
        "background_color_live_wear_difference": "#222222",
        "show_lifespan_laps": True,
        "font_color_lifespan_laps": "#CCCC22",
        "background_color_lifespan_laps": "#222222",
        "show_lifespan_minutes": True,
        "font_color_lifespan_minutes": "#66CCCC",
        "background_color_lifespan_minutes": "#222222",
        "show_caption": True,
        "font_scale_caption": 0.8,
        "caption_text_remaining": "brake wear",
        "caption_text_wear_difference": "wear diff",
        "caption_text_live_wear_difference": "live wear",
        "caption_text_lifespan_laps": "est. laps",
        "caption_text_lifespan_minutes": "est. mins",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
        "display_order_remaining": 1,
        "display_order_wear_difference": 2,
        "display_order_live_wear_difference": 3,
        "display_order_lifespan_laps": 4,
        "display_order_lifespan_minutes": 5,
    },
}
