#  TinyPedal is an open-source overlay application for racing simulation.
#  Copyright (C) 2022-2026 TinyPedal developers, see contributors.md file
#
#  This file is part of TinyPedal.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Default setting of chassis & suspension widgets

Widget key name must match corresponding file name in 'widget' folder
"""

WIDGET_CHASSIS = {
    "differential": {
        "enable": False,
        "update_interval": 20,
        "position_x": 57,
        "position_y": 860,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_inverted_locking": False,
        "decimal_places": 0,
        "off_throttle_threshold": 0.01,
        "on_throttle_threshold": 0.01,
        "power_locking_reset_cooldown": 5,
        "coast_locking_reset_cooldown": 5,
        "show_power_locking_front": True,
        "prefix_power_front": "P ",
        "font_color_power_locking_front": "#FFFFFF",
        "background_color_power_locking_front": "#222222",
        "show_coast_locking_front": True,
        "prefix_coast_front": "C ",
        "font_color_coast_locking_front": "#FFFFFF",
        "background_color_coast_locking_front": "#222222",
        "show_power_locking_rear": True,
        "prefix_power_rear": "P ",
        "font_color_power_locking_rear": "#000000",
        "background_color_power_locking_rear": "#FFFFFF",
        "show_coast_locking_rear": True,
        "prefix_coast_rear": "C ",
        "font_color_coast_locking_rear": "#000000",
        "background_color_coast_locking_rear": "#FFFFFF",
        "display_order_power_locking_front": 1,
        "display_order_coast_locking_front": 2,
        "display_order_power_locking_rear": 3,
        "display_order_coast_locking_rear": 4,
    },
    "rake_angle": {
        "enable": False,
        "update_interval": 20,
        "position_x": 593,
        "position_y": 315,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "show_degree_sign": True,
        "show_ride_height_difference": True,
        "wheelbase": 2800,
        "rake_angle_smoothing_samples": 10,
        "decimal_places": 2,
        "prefix_rake_angle": "RA ",
        "font_color_rake_angle": "#FFFFFF",
        "background_color_rake_angle": "#222222",
        "warning_color_negative_rake": "#00AAFF",
    },
    "ride_height": {
        "enable": False,
        "update_interval": 20,
        "position_x": 253,
        "position_y": 384,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "highlight_color": "#44CC00",
        "background_color": "#222222",
        "ride_height_maximum_range": 150,
        "bottoming_height_front_left": 0,
        "bottoming_height_front_right": 0,
        "bottoming_height_rear_left": 0,
        "bottoming_height_rear_right": 0,
        "warning_color_bottoming": "#FF2200",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "ride height",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "roll_angle": {
        "enable": False,
        "update_interval": 20,
        "position_x": 770,
        "position_y": 720,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_degree_and_percentage_sign": True,
        "wheel_track_front": 1800,
        "wheel_track_rear": 1800,
        "roll_angle_smoothing_samples": 10,
        "roll_angle_ratio_smoothing_samples": 50,
        "decimal_places": 2,
        "prefix_roll_angle_front": "",
        "font_color_roll_angle_front": "#FFFFFF",
        "background_color_roll_angle_front": "#222222",
        "prefix_roll_angle_rear": "",
        "font_color_roll_angle_rear": "#FFFFFF",
        "background_color_roll_angle_rear": "#222222",
        "show_roll_angle_difference": True,
        "prefix_roll_angle_difference": "",
        "font_color_roll_angle_difference": "#FFFFFF",
        "background_color_roll_angle_difference": "#0066CC",
        "show_roll_angle_ratio": True,
        "prefix_roll_angle_ratio": "",
        "font_color_roll_angle_ratio": "#000000",
        "background_color_roll_angle_ratio": "#DDDDDD",
        "display_order_roll_angle_front": 1,
        "display_order_roll_angle_rear": 2,
        "display_order_roll_angle_difference": 3,
        "display_order_roll_angle_ratio": 4,
    },
    "suspension_force": {
        "enable": False,
        "update_interval": 20,
        "position_x": 391,
        "position_y": 713,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "highlight_color": "#CC00CC",
        "background_color": "#222222",
        "show_force_ratio": True,
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "susp force",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "suspension_position": {
        "enable": False,
        "update_interval": 20,
        "position_x": 145,
        "position_y": 670,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "positive_position_color": "#FFAA00",
        "negative_position_color": "#00AAFF",
        "background_color": "#222222",
        "position_maximum_range": 100,
        "show_third_spring_position_mark": True,
        "third_spring_position_mark_width": 2,
        "third_spring_position_mark_color": "#FFFFFF",
        "show_maximum_position_range": True,
        "maximum_position_range_size": 3,
        "maximum_position_range_color": "#FF2222",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "susp pos",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "suspension_travel": {
        "enable": False,
        "update_interval": 20,
        "position_x": 728,
        "position_y": 390,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_total_travel": True,
        "font_color_total_travel": "#FFFFFF",
        "background_color_total_travel": "#222222",
        "show_bump_travel": True,
        "font_color_bump_travel": "#FFFFFF",
        "background_color_bump_travel": "#222222",
        "show_rebound_travel": True,
        "font_color_rebound_travel": "#FFFFFF",
        "background_color_rebound_travel": "#222222",
        "show_travel_ratio": True,
        "font_color_travel_ratio": "#CCCC22",
        "background_color_travel_ratio": "#222222",
        "show_motion_ratio": True,
        "font_color_motion_ratio": "#CC44CC",
        "background_color_motion_ratio": "#222222",
        "show_minimum_position": True,
        "font_color_minimum_position": "#66CCFF",
        "background_color_minimum_position": "#222222",
        "show_maximum_position": True,
        "font_color_maximum_position": "#FF6600",
        "background_color_maximum_position": "#222222",
        "show_live_position": True,
        "show_live_position_relative_to_static_position": True,
        "font_color_live_position": "#22CC22",
        "background_color_live_position": "#222222",
        "show_caption": True,
        "font_scale_caption": 0.8,
        "caption_text_total_travel": "total",
        "caption_text_bump_travel": "bump",
        "caption_text_rebound_travel": "rebound",
        "caption_text_travel_ratio": "t.ratio",
        "caption_text_motion_ratio": "m.ratio",
        "caption_text_minimum_position": "min pos",
        "caption_text_maximum_position": "max pos",
        "caption_text_live_position": "live pos",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
        "display_order_total_travel": 1,
        "display_order_bump_travel": 2,
        "display_order_rebound_travel": 3,
        "display_order_travel_ratio": 4,
        "display_order_motion_ratio": 5,
        "display_order_minimum_position": 6,
        "display_order_maximum_position": 7,
        "display_order_live_position": 8,
    },
    "weight_distribution": {
        "enable": False,
        "update_interval": 20,
        "position_x": 830,
        "position_y": 720,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_percentage_sign": True,
        "decimal_places": 1,
        "smoothing_samples": 10,
        "show_front_to_rear_distribution": True,
        "prefix_front_to_rear_distribution": "F ",
        "font_color_front_to_rear_distribution": "#FFFFFF",
        "background_color_front_to_rear_distribution": "#222222",
        "show_left_to_right_distribution": True,
        "prefix_left_to_right_distribution": "L ",
        "font_color_left_to_right_distribution": "#FFFFFF",
        "background_color_left_to_right_distribution": "#222222",
        "show_cross_weight": True,
        "prefix_cross_weight": "C ",
        "font_color_cross_weight": "#FFFFFF",
        "background_color_cross_weight": "#8800CC",
        "display_order_front_to_rear_distribution": 1,
        "display_order_left_to_right_distribution": 2,
        "display_order_cross_weight": 3,
    },
}
