#  TinyPedal is an open-source overlay application for racing simulation.
#  Copyright (C) 2022-2026 TinyPedal developers, see contributors.md file
#
#  This file is part of TinyPedal.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Default setting of race aid widgets: trends, pit lane, stint, spotter & notifications

Widget key name must match corresponding file name in 'widget' folder
"""

from ..setting_heatmap import HEATMAP_DEFAULT_TYRE

WIDGET_RACE_AIDS = {
    "delta_graph": {
        "enable": False,
        "update_interval": 50,
        "position_x": 760,
        "position_y": 800,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "display_width": 320,
        "display_height": 90,
        "deltabest_source": "Best",
        "delta_display_range": 2,
        "decimal_places": 2,
        "show_delta_reading": True,
        "show_previous_lap": True,
        "show_position_mark": True,
        "font_color_reading": "#EEEEEE",
        "background_color": "#CC222222",
        "fill_color_time_gain": "#8844FF00",
        "fill_color_time_loss": "#88FF4400",
        "line_color_current_lap": "#EEEEEE",
        "line_color_previous_lap": "#88888888",
        "zero_line_color": "#88AAAAAA",
        "position_mark_color": "#00CCFF",
    },
    "gap_trend": {
        "enable": False,
        "update_interval": 100,
        "position_x": 1200,
        "position_y": 800,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "number_of_laps": 8,
        "decimal_places": 1,
        "show_gaps_in_class": True,
        "show_driver_name": False,
        "show_closing_rate": True,
        "show_trend_chart": True,
        "font_color_caption": "#AAAAAA",
        "background_color_caption": "#222222",
        "font_color_gap": "#EEEEEE",
        "background_color_gap": "#222222",
        "font_color_gaining": "#44FF00",
        "font_color_losing": "#FF4400",
        "background_color_chart": "#2A2A2A",
        "chart_line_color": "#00CCFF",
    },
    "pit_lane_helper": {
        "enable": False,
        "update_interval": 50,
        "position_x": 820,
        "position_y": 560,
        "font_name": "Consolas",
        "font_size": 16,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.95,
        "bar_padding": 0.3,
        "show_always": False,
        "approach_distance": 400,
        "show_speed": True,
        "show_limiter_state": True,
        "show_pit_box_distance": True,
        "show_planned_services": True,
        "font_color_caption": "#AAAAAA",
        "font_color_reading": "#EEEEEE",
        "background_color": "#222222",
        "font_color_under_limit": "#44FF00",
        "font_color_over_limit": "#FF4400",
        "background_color_limiter_on": "#22CC22",
        "background_color_limiter_off": "#FF2200",
        "pit_box_bar_color": "#00CCFF",
        "background_color_pit_box_bar": "#444444",
    },
    "stint_timer": {
        "enable": False,
        "update_interval": 200,
        "position_x": 30,
        "position_y": 500,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "maximum_stint_minutes": 0,
        "stint_warning_minutes": 5,
        "show_stint_laps": True,
        "show_stint_countdown": True,
        "show_driver_times": True,
        "number_of_drivers": 0,
        "minimum_driving_minutes": 0,
        "font_color_caption": "#AAAAAA",
        "background_color_caption": "#222222",
        "font_color_reading": "#EEEEEE",
        "background_color_reading": "#222222",
        "font_color_current_driver": "#00CCFF",
        "font_color_target_met": "#44FF00",
        "font_color_warning": "#FFAA00",
        "driving_time_bar_color": "#00CCFF",
    },
    "spotter": {
        "enable": False,
        "update_interval": 20,
        "position_x": 360,
        "position_y": 360,
        "opacity": 0.9,
        "bar_width": 14,
        "bar_height": 360,
        "horizontal_gap": 1186,
        "vehicle_length": 4.6,
        "vehicle_width": 1.9,
        "nearby_side_distance": 5.0,
        "critical_side_distance": 2.6,
        "show_bar_background": False,
        "bar_color_nearby": "#FFAA00",
        "bar_color_critical": "#FF2200",
        "bar_background_color": "#44222222",
    },
    "race_notifications": {
        "enable": False,
        "update_interval": 100,
        "position_x": 760,
        "position_y": 200,
        "font_name": "Consolas",
        "font_size": 16,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.95,
        "bar_padding": 0.4,
        "layout": 0,
        "display_duration": 5,
        "number_of_notifications": 3,
        "show_position_change": True,
        "show_position_change_in_class": True,
        "show_penalty": True,
        "show_class_fastest_lap": True,
        "show_blue_flag": True,
        "show_full_course_yellow": True,
        "show_lap_invalidated": True,
        "font_color_notification": "#EEEEEE",
        "background_color_notification": "#222222",
        "highlight_color_gain": "#22CC22",
        "highlight_color_loss": "#FF2200",
        "highlight_color_warning": "#FFAA00",
        "highlight_color_info": "#0088FF",
        "highlight_color_best": "#9900FF",
    },
    "tyre_temp_trend": {
        "enable": False,
        "update_interval": 100,
        "position_x": 30,
        "position_y": 760,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "display_width": 110,
        "display_height": 40,
        "trend_duration": 120,
        "show_trend_by_lap": False,
        "number_of_laps": 10,
        "show_optimal_temperature": True,
        "show_degree_sign": True,
        "enable_heatmap_auto_matching": True,
        "heatmap_name": HEATMAP_DEFAULT_TYRE,
        "font_color_caption": "#AAAAAA",
        "background_color_caption": "#222222",
        "background_color_chart": "#2A2A2A",
        "optimal_line_color": "#AAFFFFFF",
    },
}
