#  TinyPedal is an open-source overlay application for racing simulation.
#  Copyright (C) 2022-2026 TinyPedal developers, see contributors.md file
#
#  This file is part of TinyPedal.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Default setting of timing & lap widgets

Widget key name must match corresponding file name in 'widget' folder
"""

WIDGET_TIMING = {
    "deltabest": {
        "enable": True,
        "update_interval": 20,
        "position_x": 987,
        "position_y": 372,
        "font_name": "Consolas",
        "font_size": 17,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding_horizontal": 0.5,
        "bar_padding_vertical": 0.4,
        "bar_gap": 2,
        "decimal_places": 3,
        "deltabest_source": "Best",
        "show_game_deltabest_if_available": False,
        "swap_style": False,
        "font_color_deltabest": "#000000",
        "background_color_deltabest": "#222222",
        "background_color_time_gain": "#44FF00",
        "background_color_time_loss": "#FF4400",
        "show_delta_bar": True,
        "background_color_delta_bar": "#222222",
        "delta_bar_length": 300,
        "delta_bar_height": 16,
        "delta_bar_display_range": 2,
        "delta_display_range": 99.999,
        "freeze_duration": 3,
        "enable_animated_deltabest": True,
    },
    "deltabest_extended": {
        "enable": False,
        "update_interval": 20,
        "position_x": 320,
        "position_y": 123,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 1,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "decimal_places": 3,
        "delta_display_range": 99.999,
        "freeze_duration": 3,
        "show_game_deltabest_if_available": False,
        "show_all_time_deltabest": True,
        "prefix_all_time_deltabest": "B ",
        "font_color_all_time_deltabest": "#000000",
        "background_color_all_time_deltabest": "#FFFFFF",
        "show_session_deltabest": True,
        "prefix_session_deltabest": "S ",
        "font_color_session_deltabest": "#22FFFF",
        "background_color_session_deltabest": "#222222",
        "show_stint_deltabest": True,
        "prefix_stint_deltabest": "T ",
        "font_color_stint_deltabest": "#FFFF22",
        "background_color_stint_deltabest": "#222222",
        "show_deltalast": True,
        "prefix_deltalast": "L ",
        "font_color_deltalast": "#BBBBBB",
        "background_color_deltalast": "#222222",
        "display_order_all_time_deltabest": 1,
        "display_order_session_deltabest": 2,
        "display_order_stint_deltabest": 3,
        "display_order_deltalast": 4,
    },
    "lap_time_history": {
        "enable": False,
        "update_interval": 100,
        "position_x": 523,
        "position_y": 393,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 1,
        "lap_time_history_count": 10,
        "show_empty_history": False,
        "show_laps": True,
        "font_color_laps": "#222222",
        "background_color_laps": "#CCCCCC",
        "font_color_last_laps": "#AAAAAA",
        "background_color_last_laps": "#88444444",
        "show_time": True,
        "font_color_time": "#222222",
        "font_color_invalid_time": "#FF6600",
        "background_color_time": "#EEEEEE",
        "font_color_last_time": "#AAAAAA",
        "background_color_last_time": "#88333333",
        "show_delta": True,
        "decimal_places_delta": 2,
        "font_color_delta": "#222222",
        "background_color_delta": "#EEEEEE",
        "font_color_last_delta": "#AAAAAA",
        "background_color_last_delta": "#88333333",
        "show_fuel": True,
        "show_fuel_sign": True,
        "decimal_places_fuel": 2,
        "show_virtual_energy_if_available": True,
        "font_color_fuel": "#222222",
        "background_color_fuel": "#CCCCCC",
        "font_color_last_fuel": "#AAAAAA",
        "background_color_last_fuel": "#88444444",
        "show_fuel_ratio": False,
        "decimal_places_fuel_ratio": 3,
        "font_color_fuel_ratio": "#222222",
        "background_color_fuel_ratio": "#CCCCCC",
        "font_color_last_fuel_ratio": "#AAAAAA",
        "background_color_last_fuel_ratio": "#88444444",
        "show_wear": True,
        "show_wear_sign": True,
        "decimal_places_wear": 1,
        "font_color_wear": "#222222",
        "background_color_wear": "#EEEEEE",
        "font_color_last_wear": "#AAAAAA",
        "background_color_last_wear": "#88333333",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text_laps": "laps",
        "caption_text_time": "time",
        "caption_text_delta": "delta",
        "caption_text_fuel": "fuel",
        "caption_text_virtual_energy": "nrg",
        "caption_text_fuel_ratio": "ratio",
        "caption_text_wear": "wear",
        "swap_upper_caption": False,
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
        "display_order_laps": 1,
        "display_order_time": 2,
        "display_order_delta": 3,
        "display_order_fuel": 4,
        "display_order_fuel_ratio": 5,
        "display_order_wear": 6,
    },
    "laps_and_position": {
        "enable": False,
        "update_interval": 100,
        "position_x": 57,
        "position_y": 42,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 1,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_laps": True,
        "show_predicted_extra_laps": True,
        "prefix_laps": "L",
        "font_color_laps": "#000000",
        "background_color_laps": "#FFFFFF",
        "warning_color_maximum_laps": "#FF0000",
        "show_position_overall": True,
        "prefix_position_overall": "P ",
        "font_color_position_overall": "#FFFFFF",
        "background_color_position_overall": "#222222",
        "show_position_in_class": True,
        "prefix_position_in_class": "C ",
        "font_color_position_in_class": "#FFFFFF",
        "background_color_position_in_class": "#666666",
        "show_track_limits_points": True,
        "prefix_track_limits_points": "T ",
        "font_color_track_limits_points": "#FFFFFF",
        "background_color_track_limits_points": "#222222",
        "show_position_change": True,
        "show_position_change_in_class": True,
        "font_color_position_same": "#AAAAAA",
        "background_color_position_same": "#222222",
        "font_color_position_gain": "#66EE00",
        "background_color_position_gain": "#222222",
        "font_color_position_loss": "#EE6600",
        "background_color_position_loss": "#222222",
        "display_order_laps": 1,
        "display_order_position_overall": 2,
        "display_order_position_in_class": 3,
        "display_order_track_limits_points": 4,
        "display_order_position_change": 5,
    },
    "sectors": {
        "enable": False,
        "update_interval": 20,
        "position_x": 57,
        "position_y": 157,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "enable_all_time_best_sectors": True,
        "target_laptime": "Theoretical",
        "freeze_duration": 5,
        "show_formatted_sector_time": True,
        "extra_digits": 2,
        "font_color_target_time": "#AAAAAA",
        "background_color_target_time": "#222222",
        "font_color_current_time": "#FFFFFF",
        "background_color_current_time": "#222222",
        "font_color_sector": "#AAAAAA",
        "background_color_sector": "#222222",
        "font_color_sector_highlighted": "#FFFFFF",
        "font_color_time_gain": "#22CC22",
        "font_color_time_loss": "#BBAA00",
        "background_color_time_gain": "#008800",
        "background_color_time_loss": "#887700",
        "display_order_target_time": 0,
        "display_order_sector_time": 1,
    },
    "stint_history": {
        "enable": False,
        "update_interval": 100,
        "position_x": 523,
        "position_y": 423,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 1,
        "stint_history_count": 2,
        "show_empty_history": False,
        "show_laps": True,
        "font_color_laps": "#222222",
        "background_color_laps": "#CCCCCC",
        "font_color_last_stint_laps": "#AAAAAA",
        "background_color_last_stint_laps": "#88444444",
        "show_time": True,
        "font_color_time": "#222222",
        "background_color_time": "#EEEEEE",
        "font_color_last_stint_time": "#AAAAAA",
        "background_color_last_stint_time": "#88333333",
        "show_fuel": True,
        "show_fuel_sign": True,
        "decimal_places_fuel": 3,
        "show_virtual_energy_if_available": True,
        "font_color_fuel": "#222222",
        "background_color_fuel": "#CCCCCC",
        "font_color_last_stint_fuel": "#AAAAAA",
        "background_color_last_stint_fuel": "#88444444",
        "show_tyre": True,
        "font_color_tyre": "#222222",
        "background_color_tyre": "#EEEEEE",
        "font_color_last_stint_tyre": "#AAAAAA",
        "background_color_last_stint_tyre": "#88333333",
        "show_wear": True,
        "show_wear_sign": True,
        "decimal_places_wear": 2,
        "font_color_wear": "#222222",
        "background_color_wear": "#CCCCCC",
        "font_color_last_stint_wear": "#AAAAAA",
        "background_color_last_stint_wear": "#88444444",
        "show_delta": True,
        "decimal_places_delta": 2,
        "font_color_delta": "#222222",
        "background_color_delta": "#EEEEEE",
        "font_color_last_stint_delta": "#AAAAAA",
        "background_color_last_stint_delta": "#88333333",
        "show_consistency": True,
        "show_consistency_sign": True,
        "decimal_places_consistency": 2,
        "font_color_consistency": "#222222",
        "background_color_consistency": "#CCCCCC",
        "font_color_last_stint_consistency": "#AAAAAA",
        "background_color_last_stint_consistency": "#88444444",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text_laps": "laps",
        "caption_text_time": "time",
        "caption_text_fuel": "fuel",
        "caption_text_virtual_energy": "nrg",
        "caption_text_tyre": "tyre",
        "caption_text_wear": "wear",
        "caption_text_delta": "delta",
        "caption_text_consistency": "consist",
        "swap_upper_caption": False,
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
        "display_order_laps": 1,
        "display_order_time": 2,
        "display_order_fuel": 3,
        "display_order_tyre": 4,
        "display_order_wear": 5,
        "display_order_delta": 6,
        "display_order_consistency": 7,
    },
    "timing": {
        "enable": False,
        "update_interval": 20,
        "position_x": 147,
        "position_y": 500,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "show_session_best": True,
        "show_session_best_from_same_class_only": True,
        "prefix_session_best": "S ",
        "font_color_session_best": "#44DDFF",
        "background_color_session_best": "#222222",
        "show_best": True,
        "prefix_best": "B ",
        "font_color_best": "#000000",
        "background_color_best": "#FFFFFF",
        "show_last": True,
        "prefix_last": "L ",
        "font_color_last": "#FFFFFF",
        "font_color_invalid_last": "#FF6600",
        "background_color_last": "#222222",
        "show_current": True,
        "prefix_current": "C ",
        "font_color_current": "#88FF88",
        "background_color_current": "#222222",
        "show_estimated": True,
        "prefix_estimated": "E ",
        "font_color_estimated": "#FFFF88",
        "background_color_estimated": "#222222",
        "show_session_personal_best": True,
        "prefix_session_personal_best": "P ",
        "font_color_session_personal_best": "#EE77FF",
        "background_color_session_personal_best": "#222222",
        "show_stint_best": True,
        "prefix_stint_best": "T ",
        "font_color_stint_best": "#CCCCCC",
        "background_color_stint_best": "#222222",
        "show_average_pace": True,
        "prefix_average_pace": "A ",
        "font_color_average_pace": "#AADD88",
        "background_color_average_pace": "#222222",
        "display_order_session_best": 1,
        "display_order_best": 2,
        "display_order_last": 3,
        "display_order_current": 4,
        "display_order_estimated": 5,
        "display_order_session_personal_best": 10,
        "display_order_stint_best": 15,
        "display_order_average_pace": 20,
    },
}
