#  TinyPedal is an open-source overlay application for racing simulation.
#  Copyright (C) 2022-2026 TinyPedal developers, see contributors.md file
#
#  This file is part of TinyPedal.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
Default setting of tyre & wheel widgets

Widget key name must match corresponding file name in 'widget' folder
"""

from ..setting_heatmap import HEATMAP_DEFAULT_TYRE

WIDGET_TYRES = {
    "tyre_carcass": {
        "enable": False,
        "update_interval": 20,
        "position_x": 57,
        "position_y": 670,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "inner_gap": 0,
        "swap_style": False,
        "show_degree_sign": False,
        "leading_zero": 2,
        "font_color_carcass": "#000000",
        "background_color_carcass": "#222222",
        "enable_heatmap_auto_matching": True,
        "heatmap_name": HEATMAP_DEFAULT_TYRE,
        "show_rate_of_change": True,
        "rate_of_change_interval": 5,
        "rate_of_change_smoothing_samples": 20,
        "font_color_rate_of_change": "#000000",
        "background_color_rate_of_change": "#222222",
        "font_color_rate_gain": "#FF6600",
        "font_color_rate_loss": "#66CCFF",
        "show_tyre_compound": True,
        "show_compound_color_by_type": True,
        "font_color_tyre_compound": "#666666",
        "background_color_tyre_compound": "#222222",
    },
    "tyre_deflection": {
        "enable": False,
        "update_interval": 20,
        "position_x": 502,
        "position_y": 712,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "highlight_color": "#FFFF00",
        "background_color": "#222222",
        "deflection_maximum_range": 50,
        "lift_off_threshold": 1,
        "warning_color_lift_off": "#FF2200",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "tyre deflect",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "tyre_inner_layer": {
        "enable": False,
        "update_interval": 20,
        "position_x": 249,
        "position_y": 563,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "inner_gap": 0,
        "swap_style": False,
        "show_inner_center_outer": True,
        "show_degree_sign": False,
        "leading_zero": 2,
        "font_color_inner_layer": "#000000",
        "background_color_inner_layer": "#222222",
        "enable_heatmap_auto_matching": True,
        "heatmap_name": HEATMAP_DEFAULT_TYRE,
        "show_tyre_compound": True,
        "show_compound_color_by_type": True,
        "font_color_tyre_compound": "#666666",
        "background_color_tyre_compound": "#222222",
    },
    "tyre_load": {
        "enable": False,
        "update_interval": 20,
        "position_x": 253,
        "position_y": 430,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "highlight_color": "#FFFFFF",
        "background_color": "#222222",
        "low_load_threshold": 1,
        "warning_color_low_load": "#FF2200",
        "show_tyre_load_ratio": True,
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "tyre load",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "tyre_pressure": {
        "enable": False,
        "update_interval": 20,
        "position_x": 57,
        "position_y": 383,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "inner_gap": 0,
        "swap_style": False,
        "hot_pressure_temperature_threshold": 65,
        "average_sampling_duration": 10,
        "font_color_pressure_cold": "#66CCFF",
        "font_color_pressure_hot": "#FF6600",
        "background_color_pressure": "#222222",
        "show_pressure_deviation": True,
        "font_color_pressure_deviation": "#AAAAAA",
        "background_color_pressure_deviation": "#222222",
        "show_tyre_compound": True,
        "show_compound_color_by_type": True,
        "font_color_tyre_compound": "#666666",
        "background_color_tyre_compound": "#222222",
    },
    "tyre_temperature": {
        "enable": False,
        "update_interval": 20,
        "position_x": 249,
        "position_y": 525,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "inner_gap": 0,
        "swap_style": False,
        "show_inner_center_outer": True,
        "show_degree_sign": False,
        "leading_zero": 2,
        "font_color_surface": "#000000",
        "background_color_surface": "#222222",
        "enable_heatmap_auto_matching": True,
        "heatmap_name": HEATMAP_DEFAULT_TYRE,
        "show_tyre_compound": True,
        "show_compound_color_by_type": True,
        "font_color_tyre_compound": "#666666",
        "background_color_tyre_compound": "#222222",
    },
    "tyre_wear": {
        "enable": False,
        "update_interval": 20,
        "position_x": 57,
        "position_y": 444,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "bar_padding": 0.2,
        "bar_gap": 2,
        "warning_threshold_remaining": 30,
        "warning_threshold_wear": 3,
        "warning_threshold_laps": 5,
        "warning_threshold_minutes": 6,
        "font_color_warning": "#FF2200",
        "show_remaining": True,
        "font_color_remaining": "#22CC22",
        "background_color_remaining": "#222222",
        "show_wear_difference": True,
        "font_color_wear_difference": "#CCCCCC",
        "background_color_wear_difference": "#222222",
        "show_live_wear_difference": False,
        "font_color_live_wear_difference": "#CCCCCC",
        "background_color_live_wear_difference": "#222222",
        "show_flat_spot": False,
        "font_color_flat_spot": "#CCCCCC",
        "background_color_flat_spot": "#222222",
        "show_lifespan_laps": True,
        "font_color_lifespan_laps": "#CCCC22",
        "background_color_lifespan_laps": "#222222",
        "show_lifespan_minutes": True,
        "font_color_lifespan_minutes": "#66CCCC",
        "background_color_lifespan_minutes": "#222222",
        "show_end_stint_remaining": True,
        "font_color_end_stint_remaining": "#CCCCCC",
        "background_color_end_stint_remaining": "#222222",
        "show_caption": True,
        "font_scale_caption": 0.8,
        "caption_text_remaining": "tyre wear",
        "caption_text_wear_difference": "wear diff",
        "caption_text_live_wear_difference": "live wear",
        "caption_text_flat_spot": "flat spot",
        "caption_text_lifespan_laps": "est. laps",
        "caption_text_lifespan_minutes": "est. mins",
        "caption_text_end_stint_remaining": "end tread",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
        "display_order_remaining": 1,
        "display_order_wear_difference": 2,
        "display_order_live_wear_difference": 3,
        "display_order_flat_spot": 4,
        "display_order_lifespan_laps": 5,
        "display_order_lifespan_minutes": 6,
        "display_order_end_stint_remaining": 7,
    },
    "wheel_camber": {
        "enable": False,
        "update_interval": 20,
        "position_x": 140,
        "position_y": 395,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "bar_gap": 0,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "decimal_places_camber": 2,
        "camber_smoothing_samples": 10,
        "positive_camber_threshold": 0,
        "font_color_positive_camber": "#FF6600",
        "font_color_camber": "#FFFFFF",
        "background_color_camber": "#222222",
        "show_camber_difference": True,
        "decimal_places_camber_difference": 1,
        "camber_difference_smoothing_samples": 20,
        "font_color_camber_difference": "#AAAAAA",
        "background_color_camber_difference": "#222222",
        "show_caption": True,
        "font_scale_caption": 0.8,
        "caption_text": "camber",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "wheel_status": {
        "enable": False,
        "update_interval": 20,
        "position_x": 620,
        "position_y": 560,
        "font_name": "Consolas",
        "font_size": 13,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "layout": 0,
        "display_scale": 1.0,
        "show_background": True,
        "background_color": "#222222",
        "font_color": "#CCCCCC",
        "show_caption": False,
        "caption_text": "wheels",
        "font_color_caption": "#AAAAAA",
        "background_color_caption": "#333333",
        "show_wheel_angle": True,
        "wheel_angle_multiplier": 2.0,
        "maximum_wheel_angle": 30,
        "show_tyre_temperature": True,
        "tyre_temperature_warning_threshold": 0,
        "font_color_tyre_temperature_warning": "#FF2200",
        "show_tyre_temperature_bands": False,
        "font_color_temperature": "#000000",
        "show_degree_sign": False,
        "enable_heatmap_auto_matching": True,
        "heatmap_name_tyre": "tyre_default",
        "heatmap_name_brake": "brake_default",
        "show_tyre_pressure": False,
        "enable_tyre_pressure_target": True,
        "tyre_pressure_target_minimum": 160,
        "tyre_pressure_target_maximum": 190,
        "tyre_pressure_low_color": "#00CCFF",
        "tyre_pressure_high_color": "#FF2200",
        "tyre_pressure_warning_background_color": "#222222",
        "show_tyre_wear": True,
        "tyre_wear_warning_threshold": 30,
        "tyre_wear_warning_color": "#222222",
        "font_color_tyre_wear_warning": "#FF2200",
        "show_tyre_wear_end_stint": True,
        "show_tyre_compound": False,
        "show_tyre_status": True,
        "flat_spot_threshold": 1.0,
        "wheel_puncture_color": "#FF2200",
        "wheel_flat_spot_color": "#FFAA00",
        "wheel_detached_color": "#888888",
        "show_brake_temperature": True,
        "show_brake_wear": False,
        "brake_wear_warning_threshold": 30,
        "font_color_brake_wear_warning": "#FF2200",
        "show_slip_warning": True,
        "wheel_lock_threshold": 0.2,
        "wheel_spin_threshold": 0.15,
        "slip_warning_minimum_speed": 10,
        "warning_outline_width": 3,
        "wheel_lock_color": "#FF2200",
        "wheel_spin_color": "#FFCC00",
        "show_suspension_damage": True,
        "show_body_damage": True,
        # Order matters: config dialog names each option group after its first option,
        # so the bar options come first, then the animation pair, then the colors
        "show_battery_bar": False,
        "show_battery_percentage": True,
        "battery_bar_position": "Left",
        "enable_battery_bar_animation": True,
        "battery_bar_animation_speed": 1.0,
        "battery_idle_color": "#888888",
        "battery_charge_color": "#22CC22",
        "battery_discharge_color": "#00CCFF",
        "show_rpm_leds": True,
        "number_of_rpm_leds": 10,
        "rpm_led_start_ratio": 0.6,
        "rpm_led_low_color": "#22CC22",
        "rpm_led_mid_color": "#FFCC00",
        "rpm_led_high_color": "#FF2200",
        "rpm_led_shift_color": "#00CCFF",
        "shift_flash_interval": 0.12,
        "show_abs_indicator": True,
        "abs_active_color": "#FFAA00",
        "show_tc_indicator": True,
        "tc_active_color": "#00CCFF",
        "indicator_inactive_color": "#444444",
        "font_color_indicator": "#CCCCCC",
        "font_color_indicator_active": "#000000",
        "show_brake_bias": True,
        "show_pit_limiter_indicator": True,
        "pit_active_color": "#00CCFF",
        "limiter_active_color": "#FFCC00",
        "show_gear": True,
        "font_scale_gear": 2.0,
        "font_color_gear": "#EEEEEE",
        "enable_gear_rpm_color": True,
        "gear_color_low": "#EEEEEE",
        "gear_color_mid": "#FFAA00",
        "gear_color_shift": "#FF2200",
        "gear_mid_rpm_ratio": 0.8,
        "enable_shift_flash": True,
        "show_speed": True,
        "font_scale_speed": 1.0,
        "show_rpm": True,
        "font_scale_rpm": 0.75,
        "rpm_bar_color": "#00CCFF",
        "rpm_redline_color": "#FF2200",
        "rpm_redline_ratio": 0.95,
        "show_pedal_bars": True,
        "throttle_color": "#22CC22",
        "brake_color": "#FF2200",
        "show_refuel": True,
        "show_refill": True,
        "show_fuel_remaining": True,
        "show_energy_remaining": True,
        "info_background_color": "#333333",
        "font_color_info_label": "#AAAAAA",
        "display_order_abs": 1,
        "display_order_tc": 2,
        "display_order_brake_bias": 3,
        "display_order_pit_limiter": 4,
        "display_order_gear": 5,
        "display_order_speed": 6,
        "display_order_rpm": 7,
        "display_order_pedals": 8,
    },
    "wheel_toe": {
        "enable": False,
        "update_interval": 20,
        "position_x": 140,
        "position_y": 447,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding": 0.2,
        "bar_gap": 0,
        "horizontal_gap": 0,
        "vertical_gap": 0,
        "enable_symmetric_toe_angle": True,
        "decimal_places_toe_angle": 2,
        "toe_angle_smoothing_samples": 10,
        "font_color_toe_angle": "#FFFFFF",
        "background_color_toe_angle": "#222222",
        "show_total_toe_angle": True,
        "decimal_places_total_toe_angle": 2,
        "total_toe_angle_smoothing_samples": 20,
        "font_color_total_toe_angle_positive": "#FF6600",
        "font_color_total_toe_angle_negative": "#66CCFF",
        "background_color_total_toe_angle": "#222222",
        "show_caption": True,
        "font_scale_caption": 0.8,
        "caption_text": "toe angle",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "slip_angle": {
        "enable": False,
        "update_interval": 20,
        "position_x": 612,
        "position_y": 712,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 1,
        "slip_angle_maximum_range": 15,
        "minimum_oversteer_slip_angle_difference": -1.0,
        "minimum_understeer_slip_angle_difference": 1.5,
        "font_color": "#AAAAAA",
        "neutral_slip_angle_color": "#FFFFFF",
        "oversteer_slip_angle_color": "#00AAFF",
        "understeer_slip_angle_color": "#FFAA00",
        "background_color": "#222222",
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "slip angle",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
    "slip_ratio": {
        "enable": False,
        "update_interval": 20,
        "position_x": 280,
        "position_y": 712,
        "font_name": "Consolas",
        "font_size": 15,
        "font_weight": "Bold",
        "enable_auto_font_offset": True,
        "font_offset_vertical": 0,
        "opacity": 0.9,
        "bar_padding_horizontal": 0.4,
        "bar_padding_vertical": 0.3,
        "bar_width": 50,
        "bar_gap": 2,
        "horizontal_gap": 2,
        "vertical_gap": 2,
        "decimal_places": 0,
        "font_color": "#AAAAAA",
        "background_color": "#222222",
        "optimal_slip_ratio_color": "#FFFFFF",
        "critical_slip_ratio_color": "#FF00FF",
        "slip_ratio_optimal_range": 30,
        "slip_ratio_maximum_range": 50,
        "show_caption": False,
        "font_scale_caption": 0.8,
        "caption_text": "slip ratio",
        "font_color_caption": "#CCCCCC",
        "background_color_caption": "#777777",
    },
}
